# Generated by Django 3.0.4 on 2020-05-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20200514_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideascontainer',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High task priority'), (2, 'Medium task priority'), (3, 'Low task priority')], default=3, unique=True, verbose_name='priority'),
        ),
    ]
