# Generated by Django 3.0.4 on 2020-05-16 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import root.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0006_auto_20200515_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['send_date']},
        ),
        migrations.AddField(
            model_name='idea',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idea',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(root.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='idea',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Priority'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='priority',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High task priority'), (2, 'Medium task priority'), (3, 'Low task priority')], default=3, unique=True),
        ),
    ]
