# Generated by Django 2.2.12 on 2020-06-22 04:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_auto_20200529_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='idea',
            name='text',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsnew',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='whatsnew',
            name='text',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='whatsnew',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
