# Generated by Django 2.2.12 on 2020-07-02 19:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import root.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0010_auto_20200622_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Category title')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=models.SET(root.models.get_sentinel_user), related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='IdeaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid tag name', regex='^[a-zA-Z0-9_]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Invalid tag name', regex='^[a-zA-Z]+$')])),
                ('text', models.TextField(unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('answered', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['create_date'],
            },
        ),
        migrations.RemoveField(
            model_name='whatsnew',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['create_date']},
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='send_date',
            new_name='create_date',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='priority',
        ),
        migrations.AddField(
            model_name='idea',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='idea',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(root.models.get_sentinel_user), related_name='ideas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
        migrations.DeleteModel(
            name='WhatsNew',
        ),
        migrations.AddField(
            model_name='ideacomment',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='root.Idea'),
        ),
        migrations.AddField(
            model_name='idea',
            name='tags',
            field=models.ManyToManyField(related_name='ideas', to='root.IdeaTag'),
        ),
    ]
