# Generated by Django 2.2.12 on 2020-07-03 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_auto_20200702_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='root.IdeaCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idea',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ideas', to='root.IdeaTag'),
        ),
    ]
