# Generated by Django 3.0.4 on 2020-04-17 01:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0004_auto_20200416_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
