# Generated by Django 3.0.4 on 2020-04-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_workspace_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='public',
            field=models.BooleanField(default=False, verbose_name='public'),
        ),
    ]
