# Generated by Django 3.0.4 on 2020-04-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_auto_20200417_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='public',
            field=models.BooleanField(default=False, verbose_name='public'),
        ),
    ]
