# Generated by Django 3.0.4 on 2020-04-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_room_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, max_length=50, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='password',
            field=models.CharField(blank=True, max_length=50, verbose_name='password'),
        ),
    ]
