# Generated by Django 3.0.4 on 2020-05-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_auto_20200422_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hidden',
            field=models.BooleanField(default=True, verbose_name='hidden'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='hidden',
            field=models.BooleanField(default=True, verbose_name='hidden'),
        ),
    ]
