# Generated by Django 2.2.12 on 2020-08-19 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0011_auto_20200516_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelPermissionUserRoomInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionUserRoomInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionUserWorkspaceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='slug',
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['id'], name='workspace_m_id_5242b1_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['id'], name='workspace_r_id_bbd2ff_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['id'], name='workspace_w_id_08e54e_idx'),
        ),
        migrations.AddField(
            model_name='permissionuserworkspaceinstance',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.Permission'),
        ),
        migrations.AddField(
            model_name='permissionuserworkspaceinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionuserworkspaceinstance',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.Workspace'),
        ),
        migrations.AddField(
            model_name='permissionuserroominstance',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.Permission'),
        ),
        migrations.AddField(
            model_name='permissionuserroominstance',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.Room'),
        ),
        migrations.AddField(
            model_name='permissionuserroominstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='levelpermissionuserroominstance',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.Permission'),
        ),
        migrations.AddField(
            model_name='levelpermissionuserroominstance',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.Room'),
        ),
        migrations.AddField(
            model_name='levelpermissionuserroominstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='permissionuserworkspaceinstance',
            constraint=models.UniqueConstraint(fields=('user', 'workspace', 'permission'), name='unique_permission_workspace_user'),
        ),
        migrations.AddConstraint(
            model_name='permissionuserroominstance',
            constraint=models.UniqueConstraint(fields=('user', 'room', 'permission'), name='unique_permission_room_user'),
        ),
        migrations.AddConstraint(
            model_name='levelpermissionuserroominstance',
            constraint=models.UniqueConstraint(fields=('user', 'room'), name='unique_level_permission_room_user'),
        ),
    ]
