# Generated by Django 3.0.4 on 2020-05-13 00:38

from django.conf import settings
from django.db import migrations, models
import root.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('text', models.TextField()),
                ('priority', models.IntegerField(choices=[(1, 'Hight'), (2, 'Medium'), (3, 'Low')], default=3)),
                ('author', models.ForeignKey(on_delete=models.SET(root.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
    ]
