# Generated by Django 3.0.4 on 2020-05-14 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeasContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('priority', models.IntegerField(choices=[(1, 'High task priority'), (2, 'Medium task priority'), (3, 'Low task priority')], verbose_name='priority')),
            ],
        ),
        migrations.RemoveField(
            model_name='idea',
            name='priority',
        ),
        migrations.AlterField(
            model_name='idea',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AddField(
            model_name='idea',
            name='ideas_container',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='root.IdeasContainer', verbose_name='ideas_container'),
            preserve_default=False,
        ),
    ]
