# Generated by Django 3.0.4 on 2020-05-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20200514_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideascontainer',
            name='title',
        ),
        migrations.AlterField(
            model_name='ideascontainer',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High task priority'), (2, 'Medium task priority'), (3, 'Low task priority')], default=3, verbose_name='priority'),
        ),
    ]
