# Generated by Django 3.0.4 on 2020-05-15 23:30

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False # **<<< HERE**
    dependencies = [
        ('root', '0005_auto_20200515_2324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdeasContainer',
            new_name='Priority',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='ideas_container',
            new_name='priority',
        ),
    ]
