# Generated by Django 3.0 on 2020-05-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_auto_20200516_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-send_date']},
        ),
        migrations.AlterModelOptions(
            name='whatsnew',
            options={'ordering': ['-send_date']},
        ),
    ]
