# Generated by Django 2.2.12 on 2020-05-29 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_auto_20200516_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-send_date']},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['priority']},
        ),
        migrations.AlterModelOptions(
            name='whatsnew',
            options={'ordering': ['-send_date']},
        ),
    ]
